Repository dillonzq/LoveIt, pull requests merged in 2020-05, with the labels that each got.

#299 fix(title): terms title error and change delimiter from "|" to "-"
  exampleSite/content/posts/basic-markdown-syntax.en.md
  exampleSite/content/posts/basic-markdown-syntax.fr.md
  exampleSite/content/posts/basic-markdown-syntax.zh-cn.md
  layouts/404.html
  layouts/_default/baseof.html
  layouts/_default/section.html
  layouts/_default/single.html
  layouts/posts/rss.xml
  layouts/posts/single.html
  layouts/taxonomy/list.html
  layouts/taxonomy/rss.xml
  layouts/taxonomy/terms.html
Labels: bug

#301 feat(rss): add rssFullText param for RSS
  assets/css/_partial/_single/_toc.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-content.en.md
  exampleSite/content/posts/theme-documentation-content.fr.md
  exampleSite/content/posts/theme-documentation-content.zh-cn.md
  layouts/_default/_markup/render-image.html
  layouts/_default/summary.html
  layouts/index.rss.xml
  layouts/partials/assets.html
  layouts/partials/header.html
  layouts/partials/home/profile.html
  layouts/partials/plugin/image.html
  layouts/partials/plugin/share.html
  layouts/partials/rss/item.html
  layouts/posts/rss.xml
  layouts/posts/single.html
  layouts/shortcodes/echarts.html
  layouts/shortcodes/mapbox.html
  layouts/shortcodes/mermaid.html
  layouts/shortcodes/style.html
  layouts/shortcodes/typeit.html
  layouts/shortcodes/version.html
  layouts/taxonomy/rss.xml
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  src/js/theme.js
Labels: configuration, documentation, enhancement

#302 feat(search): add absoluteURL config for search index
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/index.json
Labels: configuration, documentation, enhancement

#303 Release v0.2.4
  assets/css/_partial/_single/_toc.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/basic-markdown-syntax.en.md
  exampleSite/content/posts/basic-markdown-syntax.fr.md
  exampleSite/content/posts/basic-markdown-syntax.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-content.en.md
  exampleSite/content/posts/theme-documentation-content.fr.md
  exampleSite/content/posts/theme-documentation-content.zh-cn.md
  layouts/404.html
  layouts/_default/_markup/render-image.html
  layouts/_default/baseof.html
  layouts/_default/section.html
  layouts/_default/single.html
  layouts/_default/summary.html
  layouts/index.json
  layouts/index.rss.xml
  layouts/partials/assets.html
  layouts/partials/header.html
  layouts/partials/home/profile.html
  layouts/partials/plugin/image.html
  layouts/partials/plugin/share.html
  layouts/partials/rss/item.html
  layouts/posts/rss.xml
  layouts/posts/single.html
  layouts/shortcodes/echarts.html
  layouts/shortcodes/mapbox.html
  layouts/shortcodes/mermaid.html
  layouts/shortcodes/style.html
  layouts/shortcodes/typeit.html
  layouts/shortcodes/version.html
  layouts/taxonomy/list.html
  layouts/taxonomy/rss.xml
  layouts/taxonomy/terms.html
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  src/js/theme.js
Labels: release

#310 fix(search): theme.js error when search is disabled
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  layouts/_default/baseof.html
  src/js/theme.js
  theme.toml
Labels: bug

#314 feat(typeit): add some config for TypeIt
  assets/css/_core/_layout.scss
  assets/css/_partial/_footer.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  assets/lib/VERSION
  assets/lib/typeit/typeit.min.js
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/partials/assets.html
  layouts/partials/header.html
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  src/js/theme.js
Labels: configuration, documentation, enhancement

#315 fix(hugo): compatibility for Hugo basic version
  .gitignore
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.fr.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.zh-cn.md
  images/tn.png
  layouts/partials/function/id.html
  layouts/shortcodes/style.html
  resources/_gen/assets/scss/stype/id-1.scss_ff2a8d7d59c25f259218399bceecc7ea.content
  resources/_gen/assets/scss/stype/id-1.scss_ff2a8d7d59c25f259218399bceecc7ea.json
Labels: bug, configuration, documentation

#307 fix(menu): hide divider when no menus
  assets/css/_page/_home.scss
  layouts/partials/header.html
  layouts/partials/home/profile.html
Labels: bug

#308 feat(profile): Add optional title above subtitle
  assets/css/_page/_home.scss
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/partials/header.html
  layouts/partials/home/profile.html
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
Labels: configuration, documentation, enhancement

#309 Add Spanish translation
  README.md
  README.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  i18n/es.toml
Labels: documentation, translation

#317 feat(comment): add Utterances comment system
  README.md
  README.zh-cn.md
  assets/css/_partial/_single/_comment.scss
  assets/css/_variables.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/partials/comment.html
  package.json
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  src/js/theme.js
Labels: configuration, documentation, enhancement

#322 Release v0.2.5
  .gitignore
  README.md
  README.zh-cn.md
  assets/css/_core/_layout.scss
  assets/css/_page/_home.scss
  assets/css/_partial/_footer.scss
  assets/css/_partial/_single/_comment.scss
  assets/css/_variables.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  assets/lib/VERSION
  assets/lib/typeit/typeit.min.js
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.fr.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.zh-cn.md
  i18n/es.toml
  images/tn.png
  layouts/_default/baseof.html
  layouts/partials/assets.html
  layouts/partials/comment.html
  layouts/partials/function/id.html
  layouts/partials/header.html
  layouts/partials/home/profile.html
  layouts/shortcodes/style.html
  package.json
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  resources/_gen/assets/scss/stype/id-1.scss_ff2a8d7d59c25f259218399bceecc7ea.content
  resources/_gen/assets/scss/stype/id-1.scss_ff2a8d7d59c25f259218399bceecc7ea.json
  src/js/theme.js
  theme.toml
Labels: release

#327 fix(shortcode): style shortcode scss file path
  layouts/_default/baseof.html
  layouts/shortcodes/style.html
  resources/_gen/assets/scss/style/06219b515bd3039bce88e4417e803b29/id-1.scss_3bfbc84092731480b8d374981b54d253.content
  resources/_gen/assets/scss/style/06219b515bd3039bce88e4417e803b29/id-1.scss_3bfbc84092731480b8d374981b54d253.json
  resources/_gen/assets/scss/style/2d4250d7b4edf7b7647e94cfdc183b86/id-1.scss_e5494f82a408608c874431b5dcdb4f1e.content
  resources/_gen/assets/scss/style/2d4250d7b4edf7b7647e94cfdc183b86/id-1.scss_e5494f82a408608c874431b5dcdb4f1e.json
  resources/_gen/assets/scss/style/2f6a44c07cd36aed63db163b9f515d63/id-1.scss_4bcd2a22db7c9ce77fc96c1aa4d683bd.content
  resources/_gen/assets/scss/style/2f6a44c07cd36aed63db163b9f515d63/id-1.scss_4bcd2a22db7c9ce77fc96c1aa4d683bd.json
  resources/_gen/assets/scss/style/387e497be0b7dbdc903468dec88ce042/id-1.scss_66d6eb926874a089016353786f28e165.content
  resources/_gen/assets/scss/style/387e497be0b7dbdc903468dec88ce042/id-1.scss_66d6eb926874a089016353786f28e165.json
  resources/_gen/assets/scss/style/409594da26069e6252388311312abfd5/id-1.scss_78b750e0fe281aa9b91566ae181c2e40.content
  resources/_gen/assets/scss/style/409594da26069e6252388311312abfd5/id-1.scss_78b750e0fe281aa9b91566ae181c2e40.json
  resources/_gen/assets/scss/style/7857d7858fcfb859deeb60f29672cffc/id-1.scss_0d902f60eb581fec9411dd1846631db7.content
  resources/_gen/assets/scss/style/7857d7858fcfb859deeb60f29672cffc/id-1.scss_0d902f60eb581fec9411dd1846631db7.json
  resources/_gen/assets/scss/style/c17d91e847fcfcd8e30a3c3f56b6af46/id-1.scss_a7b5c907db9ad46c812c6b1bf9d871a7.content
  resources/_gen/assets/scss/style/c17d91e847fcfcd8e30a3c3f56b6af46/id-1.scss_a7b5c907db9ad46c812c6b1bf9d871a7.json
  resources/_gen/assets/scss/style/f34bb62f734d1cecaa4de6a8b8efab52/id-1.scss_da37cb970ff275a236f7c8e80f90244b.content
  resources/_gen/assets/scss/style/f34bb62f734d1cecaa4de6a8b8efab52/id-1.scss_da37cb970ff275a236f7c8e80f90244b.json
  resources/_gen/assets/scss/style/fb3ada7a67e15e6dfbcd8e86e0e7fb61/id-1.scss_8bcb276b6f7024fb75f6398ae3519592.content
  resources/_gen/assets/scss/style/fb3ada7a67e15e6dfbcd8e86e0e7fb61/id-1.scss_8bcb276b6f7024fb75f6398ae3519592.json
  resources/_gen/assets/scss/stype/id-1.scss_ff2a8d7d59c25f259218399bceecc7ea.json
Labels: bug

#328 feat(comment): add comment for single page and emoji config for Valine
  assets/data/emoji/apple.yml
  assets/data/emoji/facebook.yml
  assets/data/emoji/google.yml
  assets/data/emoji/twitter.yml
  assets/data/social.yml
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/_default/single.html
  layouts/partials/comment.html
  layouts/partials/home/profile.html
Labels: configuration, documentation, enhancement

#326 Add german translation, updated README
  README.md
  README.zh-cn.md
  i18n/de.toml
Labels: translation

#324 Added Serbian translation
  README.md
  README.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/it.toml
  i18n/pl.toml
  i18n/pt-BR.toml
  i18n/sr.toml
  i18n/zh-CN.toml
  layouts/partials/assets.html
Labels: translation

#330 fix(typeit): typeit shortcode newline error
  layouts/shortcodes/typeit.html
Labels: bug

#349 feat(analytics): update Google analytics.js to gtag.js
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/_default/baseof.html
  layouts/partials/plugin/analytics.html
Labels: configuration, documentation, enhancement

#350 fix(paginate): paginate error for empty content
  layouts/_default/section.html
  layouts/index.html
  layouts/taxonomy/list.html
Labels: bug

#351 fix(compatibility): compatibility for version 0.1.X
  layouts/_default/baseof.html
  layouts/partials/assets.html
  layouts/partials/comment.html
  layouts/posts/single.html
Labels: bug

#352 feat(compatibility): improve compatibility for Hugo basic version
  assets/css/_core/_media.scss
  assets/css/_mixin/_index.scss
  assets/css/_mixin/_summary.scss
  assets/css/_page/_home.scss
  assets/css/_page/_index.scss
  assets/css/_partial/_header.scss
  assets/css/_partial/_single/_toc.scss
  assets/css/_variables.scss
  assets/css/style.template.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  layouts/_default/baseof.html
  layouts/index.html
  layouts/partials/head/link.html
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.json
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.json
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.content
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.json
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.json
  src/js/theme.js
Labels: documentation, enhancement

#353 feat(CDN): replace CDN config with CDN data file
  assets/data/cdn/jsdelivr.yml
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  layouts/_default/baseof.html
  layouts/partials/comment.html
Labels: configuration, documentation, enhancement

#354 fix(social): social links blocked by uBlock Origin
  assets/css/_page/_home.scss
  layouts/partials/home/profile.html
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.content
Labels: bug

#355 feat(cookies): add Cookie consent banner
  README.md
  README.zh-cn.md
  assets/css/_core/_base.scss
  assets/css/_partial/_cookieconsent.scss
  assets/data/cdn/jsdelivr.yml
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  assets/lib/VERSION
  assets/lib/cookieconsent/cookieconsent.min.css
  assets/lib/cookieconsent/cookieconsent.min.js
  exampleSite/config.toml
  exampleSite/content/about/index.en.md
  exampleSite/content/about/index.fr.md
  exampleSite/content/about/index.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/it.toml
  i18n/pl.toml
  i18n/pt-BR.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sr.toml
  i18n/zh-CN.toml
  layouts/partials/assets.html
  layouts/partials/comment.html
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.content
  src/js/theme.js
Labels: configuration, documentation, enhancement

#356 feat(home): home profile title support HTML format
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  layouts/partials/home/profile.html
Labels: configuration, documentation, enhancement

#357 feat(page): add custom page library support (css and js)
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  exampleSite/content/posts/theme-documentation-content/index.en.md
  exampleSite/content/posts/theme-documentation-content/index.fr.md
  exampleSite/content/posts/theme-documentation-content/index.zh-cn.md
  layouts/partials/assets.html
Labels: configuration, documentation, enhancement

#359 feat(shortcode): add script shortcode
  README.md
  README.zh-cn.md
  exampleSite/content/about/index.en.md
  exampleSite/content/about/index.fr.md
  exampleSite/content/about/index.zh-cn.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes/index.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes/index.fr.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes/index.zh-cn.md
  layouts/partials/assets.html
  layouts/partials/comment.html
  layouts/partials/function/id.html
  layouts/partials/head/link.html
  layouts/partials/plugin/script.html
  layouts/partials/plugin/style.html
  layouts/partials/scratch/style.html
  layouts/partials/scratch/stylesheet.html
  layouts/shortcodes/script.html
  layouts/shortcodes/style.html
Labels: configuration, documentation, enhancement

#360 feat(style): change custom style file path
  assets/css/_custom.scss
  assets/css/_override.scss
  assets/css/_variables.scss
  assets/css/style.scss
  exampleSite/assets/css/_custom.scss
  exampleSite/assets/css/_override.scss
  exampleSite/config/css/_override.scss
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  layouts/partials/head/link.html
  resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
  resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.json
Labels: documentation, enhancement

#366 fix(format): string format error
  layouts/_default/section.html
  layouts/partials/footer.html
  layouts/partials/init.html
  layouts/partials/single/footer.html
  layouts/posts/rss.xml
  layouts/taxonomy/terms.html
Labels: bug

#363 fix(rss): fix self atom:link.
  layouts/index.rss.xml
Labels: bug

#371 i18n: update i18n string format
  assets/css/_partial/_single/_footer.scss
  assets/data/social.yml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/it.toml
  i18n/pl.toml
  i18n/pt-BR.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sr.toml
  i18n/zh-CN.toml
  layouts/404.html
  layouts/_default/section.html
  layouts/_default/summary.html
  layouts/index.json
  layouts/partials/comment.html
  layouts/partials/footer.html
  layouts/partials/home/profile.html
  layouts/partials/init.html
  layouts/partials/plugin/analytics.html
  layouts/partials/plugin/compatibility.html
  layouts/partials/plugin/icon.html
  layouts/partials/plugin/social.html
  layouts/partials/single/footer.html
  layouts/posts/rss.xml
  layouts/posts/single.html
  layouts/shortcodes/style.html
  layouts/shortcodes/typeit.html
  layouts/shortcodes/version.html
  layouts/taxonomy/list.html
  layouts/taxonomy/terms.html
  package.json
  resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
Labels: bug, translation

#368 fix(path): broken tag/category link when containing a dot
  layouts/_default/summary.html
  layouts/partials/function/path.html
  layouts/partials/single/footer.html
  layouts/posts/single.html
Labels: bug

#367 feat(lunr): some optimizing lib/lunr/*.js
  assets/lib/lunr/lunr.TinySegmenter.js
  assets/lib/lunr/lunr.ar.js
  assets/lib/lunr/lunr.da.js
  assets/lib/lunr/lunr.de.js
  assets/lib/lunr/lunr.du.js
  assets/lib/lunr/lunr.es.js
  assets/lib/lunr/lunr.fr.js
  assets/lib/lunr/lunr.hu.js
  assets/lib/lunr/lunr.it.js
  assets/lib/lunr/lunr.ja.js
  assets/lib/lunr/lunr.nl.js
  assets/lib/lunr/lunr.no.js
  assets/lib/lunr/lunr.pt.js
  assets/lib/lunr/lunr.ru.js
  assets/lib/lunr/lunr.stemmer.support.js
  assets/lib/lunr/lunr.sv.js
  assets/lib/lunr/lunr.th.js
  assets/lib/lunr/lunr.tr.js
  assets/lib/lunr/lunr.vi.js
  assets/lib/lunr/lunr.zh.js
Labels: enhancement

#372 feat(TOC): add keepStatic param for TOC
  assets/css/_partial/_single/_toc.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  exampleSite/content/posts/theme-documentation-content/index.en.md
  exampleSite/content/posts/theme-documentation-content/index.fr.md
  exampleSite/content/posts/theme-documentation-content/index.zh-cn.md
  layouts/posts/single.html
  resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
  src/js/theme.js
Labels: configuration, documentation, enhancement

#382 fix(TOC): scrollbar bug when keepStatic is true
  assets/css/_partial/_single/_toc.scss
  resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
Labels: bug

#383 feat(i18n): add Vietnamese translation
  README.md
  README.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics/index.en.md
  exampleSite/content/posts/theme-documentation-basics/index.fr.md
  exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md
  i18n/vi.toml
Labels: translation

#391 fix(404): 404 page select language error
  layouts/partials/header.html
Labels: bug

#392 feat(sitemap): improve priority
  layouts/sitemap.xml
Labels: enhancement

#394 fix(style): remove Google Font
  assets/css/_variables.scss
  resources/_gen/assets/scss/css/style.scss_d75fd08668b4bae707167bbce4d8ca46.content
Labels: bug
