Repository dillonzq/LoveIt, pull requests merged in 2020-04, with the labels that each got.

#232 fix(shortcode): fix new BV id for bilibili shortcode
  exampleSite/content/posts/theme-documentation-extended-shortcodes.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.fr.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.zh-cn.md
  layouts/shortcodes/bilibili.html
Labels: bug, documentation

#218 Add Polish translation
  i18n/pl.toml
Labels: translation

#234 chore(i18n): update Polish and docs
  README.md
  README.zh-cn.md
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  i18n/pl.toml
  package-lock.json
Labels: documentation, translation

#236 feat(compatibility): add polyfill.io to improve compatibility
  assets/lib/polyfill.yml
  layouts/partials/assets.html
Labels: enhancement

#239 feat(code): add copy button for code
  README.md
  README.zh-cn.md
  assets/css/_core/_base.scss
  assets/css/_mixin/_compatibility.scss
  assets/css/_page/_single.scss
  assets/css/_partial/_single/_code.scss
  assets/css/_variables.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  assets/lib/VERSION
  assets/lib/clipboard/clipboard.min.js
  assets/lib/polyfill.yml
  assets/svg/loading/normal.svg
  assets/svg/loading/small.svg
  assets/svg/version.template.svg
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  i18n/en.toml
  i18n/fr.toml
  i18n/pl.toml
  i18n/zh-CN.toml
  layouts/_default/baseof.html
  layouts/partials/assets.html
  layouts/partials/plugin/image.html
  layouts/shortcodes/bilibili.html
  layouts/shortcodes/version.html
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.content
  src/js/theme.js
Labels: enhancement

#246 fix: fix script CORS error
  layouts/partials/assets.html
  layouts/partials/comment.html
Labels: bug

#248 feat(home): add custom content for home page
  README.md
  README.zh-cn.md
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/_default/baseof.html
  layouts/index.html
  layouts/partials/assets.html
  layouts/partials/comment.html
  layouts/partials/plugin/analytics.html
  layouts/partials/plugin/analytics/fathom.html
  layouts/partials/plugin/script.html
  layouts/posts/single.html
  src/js/theme.js
Labels: configuration, documentation, enhancement

#250 feat: add social link for RSS and some configs
  README.md
  README.zh-cn.md
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/inde.rss.xml
  layouts/index.atom.xml
  layouts/partials/plugin/link.html
  layouts/partials/plugin/script.html
  layouts/partials/plugin/social.html
  layouts/partials/plugin/stylesheet.html
  layouts/posts/rss.xml
  layouts/shortcodes/music.html
  layouts/taxonomy/rss.xml
Labels: bug, configuration, documentation, enhancement

#251 fix: some title case bugs for section page and list page
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/categories/documentation/_index.en.md
  exampleSite/content/categories/documentation/_index.fr.md
  exampleSite/content/categories/documentation/_index.zh-cn.md
  exampleSite/content/posts/basic-markdown-syntax.en.md
  exampleSite/content/posts/basic-markdown-syntax.fr.md
  exampleSite/content/posts/basic-markdown-syntax.zh-cn.md
  exampleSite/content/posts/emoji-support.en.md
  exampleSite/content/posts/emoji-support.fr.md
  exampleSite/content/posts/emoji-support.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-built-in-shortcodes.en.md
  exampleSite/content/posts/theme-documentation-built-in-shortcodes.fr.md
  exampleSite/content/posts/theme-documentation-built-in-shortcodes.zh-cn.md
  exampleSite/content/posts/theme-documentation-content.en.md
  exampleSite/content/posts/theme-documentation-content.fr.md
  exampleSite/content/posts/theme-documentation-content.zh-cn.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.fr.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.zh-cn.md
  exampleSite/content/tags/configuration/_index.zh-cn.md
  exampleSite/content/tags/content/_index.fr.md
  exampleSite/content/tags/content/_index.zh-cn.md
  exampleSite/content/tags/installation/_index.zh-cn.md
  layouts/_default/section.html
  layouts/_default/summary.html
  layouts/index.rss.xml
  layouts/partials/single/footer.html
  layouts/posts/rss.xml
  layouts/posts/single.html
  layouts/taxonomy/list.html
  layouts/taxonomy/rss.xml
  layouts/taxonomy/terms.html
Labels: bug

#202 fix(SEO): some bad escape sequence in JSON-LD part 2
  layouts/partials/head/seo.html
Labels: bug

#252 feat(header): add Logo, pre and post config for header title
  assets/css/_page/_archive.scss
  assets/css/_page/_single.scss
  assets/css/_partial/_archive/_terms.scss
  assets/css/_partial/_header.scss
  assets/css/_partial/_single/_code.scss
  assets/css/_variables.scss
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/basic-markdown-syntax.en.md
  exampleSite/content/posts/basic-markdown-syntax.fr.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/_default/section.html
  layouts/partials/footer.html
  layouts/partials/head/seo.html
  layouts/partials/header.html
  layouts/partials/plugin/image.html
  layouts/shortcodes/version.html
  layouts/taxonomy/list.html
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.content
Labels: configuration, documentation, enhancement

#255 feat(comments): add commento.io comment system
  README.md
  README.zh-cn.md
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/partials/comment.html
Labels: configuration, documentation, enhancement

#256 chore(libs): update libs
  assets/css/_variables.scss
  assets/lib/VERSION
  assets/lib/algoliasearch/algoliasearch-lite.umd.min.js
  assets/lib/echarts/echarts.min.js
  assets/lib/fontawesome-free/all.min.css
  assets/lib/mapbox-gl/mapbox-gl.min.css
  assets/lib/mapbox-gl/mapbox-gl.min.js
  assets/lib/mermaid/mermaid.min.js
  assets/lib/smooth-scroll/smooth-scroll.min.js
  assets/lib/typeit/typeit.min.js
  assets/lib/valine/Valine.min.js
  assets/lib/valine/valine.scss
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.zh-cn.md
  layouts/partials/assets.html
  layouts/partials/comment.html
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.content
  resources/_gen/assets/scss/lib/valine/valine.scss_c443f4e76f09daefa6d3fafd13c88b9c.content
  resources/_gen/assets/scss/lib/valine/valine.scss_c443f4e76f09daefa6d3fafd13c88b9c.json
  static/lib/webfonts/fa-brands-400.eot
  static/lib/webfonts/fa-brands-400.svg
  static/lib/webfonts/fa-brands-400.ttf
  static/lib/webfonts/fa-brands-400.woff
  static/lib/webfonts/fa-brands-400.woff2
  static/lib/webfonts/fa-regular-400.eot
  static/lib/webfonts/fa-regular-400.svg
  static/lib/webfonts/fa-regular-400.ttf
  static/lib/webfonts/fa-regular-400.woff
  static/lib/webfonts/fa-regular-400.woff2
  static/lib/webfonts/fa-solid-900.eot
  static/lib/webfonts/fa-solid-900.svg
  static/lib/webfonts/fa-solid-900.ttf
  static/lib/webfonts/fa-solid-900.woff
  static/lib/webfonts/fa-solid-900.woff2
Labels: dependencies, documentation

#257 feat(style): simplify blockquote style and rm fa-fw for fontawesome syntax
  README.md
  README.zh-cn.md
  assets/css/_page/_single.scss
  assets/css/_variables.scss
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/basic-markdown-syntax.en.md
  exampleSite/content/posts/basic-markdown-syntax.fr.md
  exampleSite/content/posts/basic-markdown-syntax.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-content.en.md
  exampleSite/content/posts/theme-documentation-content.fr.md
  exampleSite/content/posts/theme-documentation-content.zh-cn.md
  layouts/partials/assets.html
  layouts/partials/function/fontawesome.html
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.content
Labels: enhancement

#259 feat(code): add support for code block folding
  assets/css/_core/_base.scss
  assets/css/_core/_media.scss
  assets/css/_page/_index.scss
  assets/css/_page/_single.scss
  assets/css/_partial/_details.scss
  assets/css/_partial/_fixed-button.scss
  assets/css/_partial/_header.scss
  assets/css/_partial/_single/_admonition.scss
  assets/css/_partial/_single/_code.scss
  assets/css/_partial/_single/_toc.scss
  assets/css/_variables.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/basic-markdown-syntax.en.md
  exampleSite/content/posts/basic-markdown-syntax.fr.md
  exampleSite/content/posts/basic-markdown-syntax.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-content.zh-cn.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.fr.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.zh-cn.md
  layouts/_default/section.html
  layouts/partials/assets.html
  layouts/posts/rss.xml
  layouts/posts/single.html
  layouts/shortcodes/admonition.html
  layouts/taxonomy/rss.xml
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.content
  src/js/theme.js
Labels: configuration, documentation, enhancement

#258 feature: add brazilian portuguese translation
  i18n/pt-BR.toml
Labels: translation

#262 docs: update theme preview and translation
  README.md
  README.zh-cn.md
  assets/css/_core/_media.scss
  assets/css/_mixin/_summary.scss
  assets/css/_page/_single.scss
  assets/css/_partial/_header.scss
  assets/css/_partial/_single/_code.scss
  assets/css/_variables.scss
  assets/lib/lunr/lunr.pt.js
  exampleSite/config/css/_override.scss
  exampleSite/content/posts/emoji-support.en.md
  exampleSite/content/posts/emoji-support.fr.md
  exampleSite/content/posts/emoji-support.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-content.en.md
  exampleSite/content/posts/theme-documentation-content.fr.md
  exampleSite/content/posts/theme-documentation-content.zh-cn.md
  exampleSite/static/images/Apple-Devices-Preview.png
  exampleSite/static/images/theme-documentation-basics/basic-configuration-preview.png
  exampleSite/static/images/theme-documentation-basics/basic-configuration-preview.zh-cn.png
  exampleSite/static/images/theme-documentation-basics/complete-configuration-preview.png
  exampleSite/static/images/theme-documentation-basics/complete-configuration-preview.zh-cn.png
  exampleSite/static/images/theme-documentation-basics/language-switch.gif
  exampleSite/static/images/theme-documentation-content/summary.jpg
  exampleSite/static/images/theme-documentation-content/summary.png
  exampleSite/static/images/theme-documentation-content/summary.zh-cn.png
  i18n/en.toml
  i18n/fr.toml
  i18n/pl.toml
  i18n/pt-BR.toml
  i18n/zh-CN.toml
  images/Apple-Devices-Preview.png
  images/screenshot.png
  images/tn.png
  layouts/404.html
  layouts/_default/section.html
  layouts/index.html
  layouts/partials/head/link.html
  layouts/partials/plugin/image.html
  layouts/partials/single/footer.html
  layouts/posts/single.html
  layouts/shortcodes/style.html
  layouts/shortcodes/version.html
  layouts/taxonomy/list.html
  package.json
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.json
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.json
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.content
  resources/_gen/assets/scss/css/style.template.scss_b8ba9a60a151126bfcde1421dc0b972d.json
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.json
Labels: bug, documentation

#261 Add permalink to a featured images on the home page
  layouts/_default/summary.html
Labels: enhancement

#260 Support favicon color theming
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/partials/head/link.html
  layouts/partials/head/meta.html
Labels: configuration, documentation, enhancement

#263 feat(style): improve style shortcode to support nesting
  assets/css/_mixin/_summary.scss
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.en.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.fr.md
  exampleSite/content/posts/theme-documentation-extended-shortcodes.zh-cn.md
  layouts/partials/head/link.html
  layouts/shortcodes/style.html
  package.json
  resources/_gen/assets/scss/css/shortcode/style.scss_19001642409beba3b4bbc3ec1bde302a.content
  resources/_gen/assets/scss/css/shortcode/style.scss_19001642409beba3b4bbc3ec1bde302a.json
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
Labels: documentation, enhancement

#264 feat(twemoji): add support for twemoji
  README.md
  README.zh-cn.md
  assets/css/_partial/_icon.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  assets/lib/VERSION
  assets/lib/twemoji/twemoji.min.js
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/emoji-support.en.md
  exampleSite/content/posts/emoji-support.fr.md
  exampleSite/content/posts/emoji-support.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/content/posts/theme-documentation-content.en.md
  exampleSite/content/posts/theme-documentation-content.fr.md
  exampleSite/content/posts/theme-documentation-content.zh-cn.md
  layouts/partials/assets.html
  resources/_gen/assets/scss/css/shortcode/style.scss_19001642409beba3b4bbc3ec1bde302a.content
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  src/js/theme.js
Labels: configuration, documentation, enhancement

#270 fix: simpleicons title override link title error
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  src/js/theme.js
Labels: bug

#271 fix(git): build panic without git
  layouts/partials/single/footer.html
Labels: bug

#272 feat(valine): add more params for new valine
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/partials/comment.html
Labels: configuration, documentation, enhancement

#273 fix(search): search icons position error on Safari Mobile
  assets/css/_partial/_header.scss
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
Labels: bug

#276 chore(github): add issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: maintenance

#277 fix: img height error in code block
  assets/css/_partial/_single/_code.scss
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
Labels: bug

#279 feat(search): add more params for search and improve search index
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  README.md
  README.zh-cn.md
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/index.json
  layouts/partials/assets.html
  layouts/shortcodes/echarts.html
  layouts/shortcodes/mapbox.html
  layouts/shortcodes/mermaid.html
  layouts/shortcodes/music.html
  layouts/shortcodes/style.html
  layouts/shortcodes/typeit.html
  src/js/theme.js
Labels: configuration, documentation, enhancement

#280 fix(code): inline code overflow-wrap
  assets/css/_core/_base.scss
  assets/css/_mixin/_compatibility.scss
  assets/css/_mixin/_summary.scss
  assets/css/_page/_single.scss
  assets/css/_partial/_archive/_tags.scss
  assets/css/_partial/_header.scss
  assets/css/_partial/_single/_code.scss
  assets/css/_partial/_single/_toc.scss
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
Labels: bug

#274 Release v0.2.1
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  README.md
  README.zh-cn.md
  assets/css/_core/_base.scss
  assets/css/_mixin/_compatibility.scss
  assets/css/_mixin/_summary.scss
  assets/css/_page/_single.scss
  assets/css/_partial/_archive/_tags.scss
  assets/css/_partial/_header.scss
  assets/css/_partial/_single/_code.scss
  assets/css/_partial/_single/_toc.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/index.json
  layouts/partials/assets.html
  layouts/shortcodes/echarts.html
  layouts/shortcodes/mapbox.html
  layouts/shortcodes/mermaid.html
  layouts/shortcodes/music.html
  layouts/shortcodes/style.html
  layouts/shortcodes/typeit.html
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  src/js/theme.js
Labels: release

#281 chore(docs): update docs
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
Labels: documentation

#282 fix(header): header style and search dropdown
  assets/css/_partial/_header.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  layouts/partials/header.html
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  src/js/theme.js
Labels: bug

#283 fix(style): link color and wrap style
  assets/css/_mixin/_compatibility.scss
  assets/css/_mixin/_link.scss
  assets/css/_mixin/_summary.scss
  assets/css/_page/_single.scss
  assets/css/_partial/_single/_code.scss
  assets/css/_partial/_single/_toc.scss
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
Labels: bug

#284 fix(typeit): typeit code highlight
  assets/css/_partial/_single/_code.scss
  layouts/_default/baseof.html
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
Labels: bug

#285 fix(style): valine dark style, header title and figure margin
  assets/css/_page/_single.scss
  assets/css/_partial/_header.scss
  assets/css/_variables.scss
  assets/lib/mermaid/mermaid.scss
  assets/lib/valine/valine.scss
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  resources/_gen/assets/scss/lib/mermaid/mermaid.scss_43d09a0fb297c4cc88d4122515a2e889.content
  resources/_gen/assets/scss/lib/valine/valine.scss_782a264805f83ff21e4b24d4d52cfa46.content
Labels: bug

#286 Release v0.2.2
  assets/css/_page/_single.scss
  assets/css/_partial/_header.scss
  assets/css/_partial/_single/_code.scss
  assets/css/_variables.scss
  assets/lib/mermaid/mermaid.scss
  assets/lib/valine/valine.scss
  exampleSite/content/posts/emoji-support.en.md
  exampleSite/content/posts/emoji-support.fr.md
  exampleSite/content/posts/emoji-support.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  layouts/_default/baseof.html
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  resources/_gen/assets/scss/lib/mermaid/mermaid.scss_43d09a0fb297c4cc88d4122515a2e889.content
  resources/_gen/assets/scss/lib/valine/valine.scss_782a264805f83ff21e4b24d4d52cfa46.content
Labels: release

#288 fix(style): global link hover color
  assets/css/_mixin/_link.scss
  assets/css/_mixin/_summary.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  src/js/theme.js
Labels: bug

#290 feat(search): improve search index by chunked separated by h2 and h3
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  layouts/index.json
  src/js/theme.js
Labels: documentation, enhancement

#293 feat: improve browser compatibility for TypeIt and object-fit
  README.md
  README.zh-cn.md
  assets/css/_core/_base.scss
  assets/css/_mixin/_compatibility.scss
  assets/css/_mixin/_link.scss
  assets/css/_mixin/_summary.scss
  assets/css/_page/_single.scss
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  assets/lib/VERSION
  assets/lib/object-fit-images/ofi.min.js
  assets/lib/typeit/typeit.min.js
  assets/svg/version.template.svg
  exampleSite/config.toml
  exampleSite/content/about.en.md
  exampleSite/content/about.fr.md
  exampleSite/content/about.zh-cn.md
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  exampleSite/static/images/Apple-Devices-Preview.png
  images/Apple-Devices-Preview.png
  layouts/partials/assets.html
  resources/_gen/assets/scss/css/style.template.scss_788c4a23da05f3aa3e03b28055a2e5f9.content
  resources/_gen/assets/scss/css/style.template.scss_84a735b886b24531b6e80c5fb2060510.content
  resources/_gen/assets/scss/css/style.template.scss_d40178ffcb058d725849178b0a7a43cc.content
  src/js/theme.js
Labels: configuration, documentation, enhancement

#294 feat(search): improve search index by rm line number in code block (#294))
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  layouts/index.json
  src/js/theme.js
Labels: enhancement

#296 feat(search): add snippetLength config for search results
  assets/js/theme.min.js
  assets/js/theme.min.js.map
  exampleSite/config.toml
  exampleSite/content/posts/theme-documentation-basics.en.md
  exampleSite/content/posts/theme-documentation-basics.fr.md
  exampleSite/content/posts/theme-documentation-basics.zh-cn.md
  src/js/theme.js
Labels: configuration, documentation, enhancement
